server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: recommendations
    group: recommendationsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

spring.data.mongodb.host: mongodb

---
spring:
  config:
    activate:
      on-profile: streaming_partitioned

spring.cloud.stream.bindings.input.consumer:
  partitioned: true
  instanceCount: 2

---
spring:
  config:
    activate:
      on-profile: streaming_instance_0

spring.cloud.stream.bindings.input.consumer:
  instanceIndex: 0

---
spring:
  config:
    activate:
      on-profile: streaming_instance_1
spring.cloud.stream.bindings.input.consumer:
  instanceIndex: 1

---
spring:
  config:
    activate:
      on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream:
  defaultBinder: kafka
