server:
  port: 7003
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    maximum-pool-size: 10
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: reviews
    group: reviewsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: streaming_partitioned

spring.cloud.stream.bindings.input.consumer:
  partitioned: true
  instanceCount: 2

---
spring:
  config:
    activate:
      on-profile: streaming_instance_0

spring.cloud.stream.bindings.input.consumer:
  instanceIndex: 0

---
spring:
  config:
    activate:
      on-profile: streaming_instance_1
spring.cloud.stream.bindings.input.consumer:
  instanceIndex: 1

---
spring:
  config:
    activate:
      on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream:
  defaultBinder: kafka
