server:
  port: 7002
  error:
    include-message: always
logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080
